### ISSUE TITLE
Unable to install peerDependencies

### ISSUE THREAD

**Issue by mattruddy** [truffle-box/arbitrum-box#8] opened 2021-07-23 02:03 UTC
I keep getting the below stack error when ever running `npm run startLocalEthereum`

<img width="934" alt="Screen Shot 2021-07-22 at 10 01 01 PM" src="https://user-images.githubusercontent.com/30830407/126729549-cc23be1c-5b06-4402-8c78-efd2aaf46ede.png">

**Comment by fainashalts** [comment] 2021-07-26 18:19
Hi @mattruddy! Did you try `npm run installLocalArbitrum` first? I am unable to reproduce, so if that doesn't work can you please share any additional info that would help me to reproduce this issue? Thanks!

**Comment by fainashalts** [comment] 2021-09-01 18:05
Hi @mattruddy I'm going to close this for issue maintenance, as I'm pretty sure that installing Arbitrum locally will help here. Feel free to open another issue if you are still having a problem with this. Thanks!

**Closed by fainashalts** 2021-09-01 18:05 UTC
